# Generated by Django 2.2.9 on 2020-01-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_page_meta', '0012_auto_20200113_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlemeta',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='keywords',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='og_description',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Facebook Description'),
        ),
        migrations.AlterField(
            model_name='titlemeta',
            name='twitter_description',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Twitter Description'),
        ),
    ]
